// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shrooms.Models;

namespace Shrooms.Migrations
{
    [DbContext(typeof(ShroomsContext))]
    partial class ShroomsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shrooms.Models.Mushroom", b =>
                {
                    b.Property<int>("MushroomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CapDimensions");

                    b.Property<string>("Family");

                    b.Property<string>("Name");

                    b.Property<bool>("Poisonous");

                    b.Property<bool>("Psycho");

                    b.Property<string>("Region");

                    b.Property<string>("SporePrintDetails");

                    b.Property<int>("StemDimensions");

                    b.Property<string>("VisualDetails");

                    b.HasKey("MushroomId");

                    b.ToTable("Mushrooms");

                    b.HasData(
                        new
                        {
                            MushroomId = 1,
                            CapDimensions = 9,
                            Family = "Pluteaceae",
                            Name = "Fly Amanita",
                            Poisonous = true,
                            Psycho = true,
                            Region = "North America, Europe, Asia",
                            SporePrintDetails = "na",
                            StemDimensions = 13,
                            VisualDetails = "white stem, red cap with white spots"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
